# Generated by Django 5.1.6 on 2026-09-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='response',
            constraint=models.UniqueConstraint(fields=('survey', 'external_id'), name='unique_survey_response'),
        ),
    ]
